return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      delay = 200,
      win = {
        border = "rounded",
      },
      layout = {
        height = { min = 4, max = 25 },
        width = { min = 20, max = 50 },
        spacing = 3,
      },
      plugins = {
        spelling = { enabled = true },
        presets = {
          operators = true,
          motions = true,
          text_objects = true,
          windows = true,
          nav = true,
          z = true,
          g = true,
        },
      },
      spec = {
        { "<leader>f",  group = "Find / Format" },
        { "<leader>ff", desc = "Find files" },
        { "<leader>fg", desc = "Grep project" },
        { "<leader>fb", desc = "Buffers" },
        { "<leader>fr", desc = "Recent files" },
        { "<leader>fh", desc = "Help" },
        { "<leader>fs", desc = "Search in buffer" },
        { "<leader>d",  desc = "Diagnostics" },
        { "<leader>n",  desc = "New file" },
        { "<leader>c",  desc = "Open config" },
        { "<leader>ca", desc = "Code actions" },
        { "<leader>p",  desc = "Plugin manager" },
        { "<leader>g",  group = "Git" },
        { "<leader>gg", desc = "LazyGit" },
        { "<leader>h",  group = "Hunk (git)" },
        { "<leader>hs", desc = "Stage hunk" },
        { "<leader>hr", desc = "Reset hunk" },
        { "<leader>hp", desc = "Preview hunk" },
        { "<leader>hb", desc = "Blame line" },
        { "<leader>rn", desc = "Rename symbol" },
        { "<leader>l",  group = "LSP" },
        { "<leader>ls", desc = "Document symbols" },
        { "<leader>m",  group = "Harpoon" },
        { "<leader>mm", desc = "Harpoon menu" },
        { "<leader>ma", desc = "Add to Harpoon" },
        { "<leader>t",  desc = "Change colorscheme" },
        { "<leader>ç",  desc = "Change font" },
      },
    },
  },
}
